name: Azure Static Web Apps CI/CD

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: azure-static-web-apps-orange-moss-0f5ea9e03-variable-group
  # Group must contain: SWA_DEPLOYMENT_TOKEN

steps:

# 1. Install Node
- task: NodeTool@0
  displayName: "Install Node.js"
  inputs:
    versionSpec: "20.x"

# 2. Install dependencies
- script: npm ci
  displayName: "Install dependencies"

# 3. Build Next.js WITH ENVIRONMENT VARIABLES
- script: |
    echo "NEXT_PUBLIC_BACKEND_URL=$NEXT_PUBLIC_BACKEND_URL" >> $GITHUB_ENV
    echo "NEXT_PUBLIC_ONBOARDING_API_URL=$NEXT_PUBLIC_ONBOARDING_API_URL" >> $GITHUB_ENV
    echo "NEXT_PUBLIC_AUTH_URL=$NEXT_PUBLIC_AUTH_URL" >> $GITHUB_ENV
    echo "NEXT_PUBLIC_CLIENT_ID=$NEXT_PUBLIC_CLIENT_ID" >> $GITHUB_ENV
    npm run build
  displayName: "Build Next.js"
  env:
    NEXT_PUBLIC_BACKEND_URL: $(NEXT_PUBLIC_BACKEND_URL)
    NEXT_PUBLIC_ONBOARDING_API_URL: $(NEXT_PUBLIC_ONBOARDING_API_URL)
    NEXT_PUBLIC_AUTH_URL: $(NEXT_PUBLIC_AUTH_URL)
    NEXT_PUBLIC_CLIENT_ID: $(NEXT_PUBLIC_CLIENT_ID)

# 4. Deploy to Azure Static Web Apps
- task: AzureStaticWebApp@0
  displayName: "Deploy to Azure Static Web Apps"
  inputs:
    azure_static_web_apps_api_token: $(SWA_DEPLOYMENT_TOKEN)
    app_location: "/"
    output_location: ".next"
