name: Azure Static Web Apps CI/CD

trigger:
  branches:
    include:
      - main

pool:
  vmImage: ubuntu-latest

variables:
  - group: azure-static-web-apps-orange-moss-0f5ea9e03-variable-group
  # This group must contain: SWA_DEPLOYMENT_TOKEN

steps:

# 1. Install Node
- task: NodeTool@0
  displayName: "Install Node.js"
  inputs:
    versionSpec: "20.x"

# 2. Install dependencies
- script: |
    npm ci
  displayName: "Install dependencies"

# 3. Build Next.js output
- script: |
    npm run build
  displayName: "Build Next.js"

# 4. Deploy to Azure Static Web Apps
- task: AzureStaticWebApp@0
  displayName: "Deploy to Azure Static Web Apps"
  inputs:
    azure_static_web_apps_api_token: $(SWA_DEPLOYMENT_TOKEN)
    app_location: "/"
    output_location: ".next"
